import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:firebase_core/firebase_core.dart';
import '../firebase_options.dart'; // generated by FlutterFire CLI

// Top-level handler for background messages.
// Must be a top-level function (not a method) — required by FCM.
// Firebase must be re-initialized here because background isolates are fresh.
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  debugPrint('BACKGROUND MESSAGE: ${message.messageId}');
}

class NotificationService {
  static final NotificationService _instance = NotificationService._internal();
  factory NotificationService() => _instance;
  NotificationService._internal();

  // Guard against duplicate listener registrations.
  // initialize() is called from _loadUserProfile() on every login;
  // without this flag each login stacks another set of listeners.
  static bool _initialized = false;

  final _messaging = FirebaseMessaging.instance;
  final _localNotifications = FlutterLocalNotificationsPlugin();

  static String? pendingReportId;
  static String? pendingNavigation;
  static VoidCallback? onNotificationTap;

  Future<void> saveToken() async {
    await _saveTokenToSupabase();
  }

  // ── Initialize everything ─────────────────────────────────────────────────
  Future<void> initialize() async {
    if (_initialized) {
      // Already set up — just refresh the token in case the user changed
      await _saveTokenToSupabase();
      return;
    }

    debugPrint('🔔 NotificationService.initialize() called');

    // Register background handler FIRST — must happen before any other FCM call
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

    // Request permission (iOS shows system dialog; Android 13+ also needs this)
    final settings = await _messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
      provisional: false,
    );

    debugPrint('Notification permission: ${settings.authorizationStatus}');

    if (settings.authorizationStatus == AuthorizationStatus.denied) {
      return;
    }

    await _setupLocalNotifications();
    await _saveTokenToSupabase();

    await _messaging.subscribeToTopic('resq_news');
    await _messaging.subscribeToTopic('resq_reports');
    await _messaging.subscribeToTopic('resq_emergency');
    debugPrint('✅ Subscribed to FCM topics');

    _messaging.onTokenRefresh.listen(_updateTokenInSupabase);

    FirebaseMessaging.onMessage.listen(_handleForegroundMessage);
    FirebaseMessaging.onMessageOpenedApp.listen(_handleNotificationTap);

    // App launched from terminated state via notification tap
    final initialMessage = await _messaging.getInitialMessage();
    if (initialMessage != null) {
      _handleNotificationTap(initialMessage);
    }

    _initialized = true;
    debugPrint('🔔 NotificationService.initialize() completed');
  }

  // ── Local notifications setup ─────────────────────────────────────────────
  Future<void> _setupLocalNotifications() async {
    const AndroidNotificationChannel channel = AndroidNotificationChannel(
      'resq_alerts',
      'ResQ Emergency Alerts',
      description: 'Critical emergency notifications from ResQ',
      importance: Importance.max,
    );

    await _localNotifications
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);

    const androidSettings =
        AndroidInitializationSettings('@mipmap/ic_launcher');

    const iosSettings = DarwinInitializationSettings(
      requestAlertPermission: false,
      requestBadgePermission: false,
      requestSoundPermission: false,
    );

    await _localNotifications.initialize(
      const InitializationSettings(
        android: androidSettings,
        iOS: iosSettings,
      ),
      onDidReceiveNotificationResponse: (details) {
        debugPrint('Local notification tapped');
        final payload = details.payload;
        if (payload == null) return;

        if (payload == 'news') {
          NotificationService.pendingNavigation = 'news';
        } else {
          final reportIdMatch =
              RegExp(r'report_id: ([^,}]+)').firstMatch(payload);
          if (reportIdMatch != null) {
            NotificationService.pendingReportId = reportIdMatch.group(1);
            NotificationService.pendingNavigation = 'report';
          }
        }

        NotificationService.onNotificationTap?.call();
      },
    );

    await _messaging.setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );
  }

  // ── Token management ──────────────────────────────────────────────────────
  Future<void> _saveTokenToSupabase() async {
    try {
      final token = await _messaging.getToken();

      debugPrint('================================================');
      debugPrint('FCM TOKEN: $token');
      debugPrint('================================================');

      if (token == null) {
        debugPrint('Token is null — device may not support FCM');
        return;
      }

      final userId =
          Supabase.instance.client.auth.currentSession?.user.id;
      if (userId == null) return;

      await Supabase.instance.client.from('users').update({
        'fcm_token': token,
        'fcm_updated_at': DateTime.now().toIso8601String(),
      }).eq('id', userId);

      debugPrint('Token saved to Supabase successfully');
    } catch (e) {
      debugPrint('Failed to save FCM token: $e');
    }
  }

  Future<void> _updateTokenInSupabase(String token) async {
    try {
      final userId =
          Supabase.instance.client.auth.currentSession?.user.id;
      if (userId == null) return;

      await Supabase.instance.client.from('users').update({
        'fcm_token': token,
        'fcm_updated_at': DateTime.now().toIso8601String(),
      }).eq('id', userId);
    } catch (e) {
      debugPrint('Failed to update FCM token: $e');
    }
  }

  Future<void> clearTokenOnLogout() async {
    try {
      final userId =
          Supabase.instance.client.auth.currentSession?.user.id;
      if (userId == null) return;

      await Supabase.instance.client.from('users').update({
        'fcm_token': null,
        'fcm_updated_at': null,
      }).eq('id', userId);

      await _messaging.deleteToken();

      // Allow re-initialization on next login
      _initialized = false;
    } catch (e) {
      debugPrint('Failed to clear FCM token: $e');
    }
  }

  // ── Message handlers ──────────────────────────────────────────────────────
  void _handleForegroundMessage(RemoteMessage message) {
    debugPrint('Foreground message: ${message.notification?.title}');

    final notification = message.notification;
    if (notification == null) return;

    _localNotifications.show(
      notification.hashCode,
      notification.title,
      notification.body,
      const NotificationDetails(
        android: AndroidNotificationDetails(
          'resq_alerts',
          'ResQ Emergency Alerts',
          channelDescription: 'Critical emergency notifications from ResQ',
          importance: Importance.max,
          priority: Priority.high,
          icon: '@mipmap/ic_launcher',
          playSound: true,
          enableVibration: true,
        ),
        iOS: DarwinNotificationDetails(
          presentAlert: true,
          presentBadge: true,
          presentSound: true,
        ),
      ),
      payload: message.data['notification_type'] == 'news'
          ? 'news'
          : message.data.toString(),
    );
  }

  void _handleNotificationTap(RemoteMessage message) {
    debugPrint('Notification tapped: ${message.data}');

    final type = message.data['notification_type'];

    if (type == 'news') {
      NotificationService.pendingNavigation = 'news';
    } else {
      final reportId = message.data['report_id'];
      if (reportId != null) {
        NotificationService.pendingReportId = reportId;
        NotificationService.pendingNavigation = 'report';
      }
    }

    // Trigger UI navigation callback if the app is already running
    NotificationService.onNotificationTap?.call();
  }
}