// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9qC27KG1EnSyok02k4ZDpBmE9SuOUXWc',
    appId: '1:894352362653:web:889fd5f41d27f725c51874',
    messagingSenderId: '894352362653',
    projectId: 'resq-app-33eb6',
    authDomain: 'resq-app-33eb6.firebaseapp.com',
    storageBucket: 'resq-app-33eb6.firebasestorage.app',
    measurementId: 'G-3FQPT4HS82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuoM3OwmRABPxZ-cecdZnmHzy02S4ZAkQ',
    appId: '1:894352362653:android:2f4f6751540c3778c51874',
    messagingSenderId: '894352362653',
    projectId: 'resq-app-33eb6',
    storageBucket: 'resq-app-33eb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs8ZGAAHSwmd-F9dPihDz_-rpQnyOiYPg',
    appId: '1:894352362653:ios:41a479476b15b362c51874',
    messagingSenderId: '894352362653',
    projectId: 'resq-app-33eb6',
    storageBucket: 'resq-app-33eb6.firebasestorage.app',
    iosBundleId: 'com.example.thesisProjectProto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs8ZGAAHSwmd-F9dPihDz_-rpQnyOiYPg',
    appId: '1:894352362653:ios:41a479476b15b362c51874',
    messagingSenderId: '894352362653',
    projectId: 'resq-app-33eb6',
    storageBucket: 'resq-app-33eb6.firebasestorage.app',
    iosBundleId: 'com.example.thesisProjectProto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9qC27KG1EnSyok02k4ZDpBmE9SuOUXWc',
    appId: '1:894352362653:web:45cd07ffa4acae30c51874',
    messagingSenderId: '894352362653',
    projectId: 'resq-app-33eb6',
    authDomain: 'resq-app-33eb6.firebaseapp.com',
    storageBucket: 'resq-app-33eb6.firebasestorage.app',
    measurementId: 'G-4ZVEKX3CB8',
  );
}
